name: Fjarå
favicon: null
layout_spectrum: 0.4888105185236782
typography_spectrum: 0.15724518871866167
title: Fjarå
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c38755'
    - '#e6b280'
    - '#f8efe6'
    - '#77482c'
    - '#371c07'
  brandStrength: 0.2045287594664842
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
